### PR TITLE
Fix issue #154 - HttpClientRequest should always be passed relative URI.

### PR DESCRIPTION
**Pull request by tbak**
HttpClientRequest and its underlying Netty's HttpRequest assume that relative URI is provided as an argument.
To always fullfil this contract I propose to deprecate methods:
`RxNetty.createHttpRequest(HttpClientRequest<ByteBuf> request)`
`RxNetty.createHttpRequest(HttpClientRequest<ByteBuf> request, HttpClient.HttpClientConfig config))`
which require creation of HttpClientRequest with absolute URI (so server/port can be extrated from it),
and replace them with equivalent methods that accept server/port explicitely as method parameters.

### CODE REVIEW

**Comment by NiteshKant** [comment]
@tbak the purpose of `RxNetty.createHttpRequest(HttpClientRequest<ByteBuf> request)`
`RxNetty.createHttpRequest(HttpClientRequest<ByteBuf> request, HttpClient.HttpClientConfig config))` was to provide an "easier" way to submit an HTTP request from a full URI.
These methods extract the server host and port from the request, defaulting the host/port if they do not exist in the URI.

The new methods you are suggesting has roughly the same creation cumbersomeness as:

``` java
RxNetty.createHttpClient("127.0.0.1", 8080).submit(HttpClientRequest.createGet("/hello"));
```

as opposed to:

``` java
RxNetty.createHttpRequest(HttpClientRequest.createGet("http://127.0.0.1:8080/hello"));
```

The former is away from the "normal" usage pattern that people have of creating a request from the full URI. This is the usecase, the existing methods are trying to solve.

**Comment by tbak** [comment]
I understand that. There are still methods like createHttpGet(String uri),etc that provide the simple usage pattern.
Going for call like this:
RxNetty.createHttpRequest(HttpClientRequest.createGet("http://127.0.0.1:8080/hello"));
has no value over the
RxNetty.createHttpGet("http://127.0.0.1:8080/hello"));
which is more compact. You may need to use RxNetty.createHttpRequest to setup more HTTP request properties (set headers, cookies, content factory, etc), and that is already more complex scenario.
I think the bigger value here is with fulfilling the HttpClientRequest contract (create object with relative URIs only), and designing RxNetty factory methods around that.

**Comment by NiteshKant** [comment]
> > > RxNetty.createHttpRequest(HttpClientRequest.createGet("http://127.0.0.1:8080/hello"));
> > > has no value over the
> > > RxNetty.createHttpGet("http://127.0.0.1:8080/hello"));

Indeed it does not but if we have this method, this can be used to make complex request started from the full URI. OTOH, if we just have `RxNetty.createHttpGet("http://127.0.0.1:8080/hello")` then the complex requests building is not additive to the simple full URI request submission.

To elaborate this, lets take an example of adding a header and a cookie. If we do not have the method `RxNetty.createHttpRequest(HttpClientRequest request)` which honors a full URI, one would have to do:

``` java
        RxNetty.createHttpClient("127.0.0.1", 8080)
               .submit(HttpClientRequest.createGet("/hello")
                                        .withHeader("Header1", "Val1")
                                        .withCookie(new DefaultCookie("mycookie", "cookieval")));
```

as opposed to:

``` java
        RxNetty.createHttpRequest(HttpClientRequest.createGet("http://127.0.0.1:8080")
                                                   .withHeader("Header1", "Val1")
                                                   .withCookie(new DefaultCookie("mycookie", "cookieval")));
```

The later is a more compact way of submitting requests and does not need people to change the approach if they have to add a header vis-a-vis just URI.

> > > I think the bigger value here is with fulfilling the HttpClientRequest contract (create object with relative URIs only), and designing RxNetty factory methods around that.

True but we can achieve this same goal by just updating the request URI in the passed `HttpClientRequest` instance, correct?

**Comment by tbak** [comment]
> True but we can achieve this same goal by just updating the request URI in the passed HttpClientRequest instance, correct?

This is what I wanted to avoid, since in some contexts we will be expecting absolute and in some relative URIs when we create HttpClientRequest. For example:

``` java
RxNetty.createHttpClient("127.0.0.1", 8080)
    .submit(HttpClientRequest.createGet("http://netflix.com/hello"));
```

Which has higher priority? We could of course report this as an error.

**Comment by NiteshKant** [comment]
It is a valid question as to what should a user expect to put as a URI in the `HttpClientRequest`

Let us outline the scenarios:
- `HttpClientRequest` has full URI and it is submitted directly to an `HTTPClient`.
- `HttpClientRequest` has full URI and it is submitted using `RxNetty.createHttpRequest` method flavors.

**Now, the contract for any HttpClient implementation (`CompositeHttpClient` and `HttpClientImpl`) is that it will _not_ introspect the URI to see if it is a full URI or not. Whatever is the URI specified will be passed as is to the server.**

This behavior with respect to scenario 1 above can be useful when the actual URI has the host and port information different than the server the request is sent on. As you had mentioned in one of our offline discussions and based on the [HTTP spec](http://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html) is a valid scenario for proxies. So, it does not make sense to disallow this scenario.

OTOH, this behavior w.r.t scenario 2 above can be rectified than what it exists today, by stripping the  scheme, host and port information from the URI in the `HttpClientRequest` before submitting to the client. IMO, this is the fix for issue #154.

**Pull request closed without merging**
