### PR TITLE
configure maxChunkSize

### PR DESCRIPTION
**Pull request by thinker0**
http://stackoverflow.com/questions/16879104/netty-4-0-0-cr3-lengthfieldbasedframedecoder-maxframelength-exceeds-integer-ma

HttpObjectAggregationConfigurator.DEFAULT_CHUNK_SIZE = 1048576;

configure maxChunkSize

### CODE REVIEW

**Comment by NiteshKant** [comment]
@thinker0 Thanks for the PR.

`PipelineConfigurators` is a utility class and does not provide all ways to configure and manipulate individual configurators. That is the reason this method overload isn't provided. 

As I understand, this can easily be done by directly initializing the `HttpObjectAggregationConfigurator` and adding it to the client. Are you facing issues in using it that way?

**Comment by thinker0** [comment]
ElasticSearch Query Result :  chunkSize 4MByte ^^;

**Comment by dimitarg** [comment]
I've a little REST client I rolled, works with rxnetty 0.4.4. Take a look:

https://github.com/dimitarg/rx-http-utils/blob/master/src/main/java/com/dgeorgiev/rx/http/client/RestClient.java

So, basically

```
private PipelineConfiguratorComposite<HttpClientResponse<ByteBuf>, HttpClientRequest<ByteBuf>> varChunksizeClientPipeline(int maxChunkSizeBytes) {
    return new PipelineConfiguratorComposite<>(new HttpClientPipelineConfigurator<ByteBuf, ByteBuf>(), new HttpObjectAggregationConfigurator(maxChunkSizeBytes));
}
```

And then 

```
    HttpClient<ByteBuf, ByteBuf> httpClient = builder.pipelineConfigurator(varChunksizeClientPipeline(maxChunksizeBytes)).build();
```

**Comment by thinker0** [comment]
^^; Thanks. ok. but default PipelineConfigurators is a utility .

**Comment by NiteshKant** [comment]
Thanks @dimitarg Thats the approach I was mentioning in my comment. 

@thinker0 Since, `PipelineConfigurators` is a utility and I would like to stay away from adding all variety of ways one can configure a `PipelineConfigurator`.

**Comment by thinker0** [comment]
@NiteshKant ok thanks.

**Pull request closed without merging**
