### PR TITLE
closing connection instead of just creating observable

### PR DESCRIPTION
**Pull request by rassmate**

### CODE REVIEW

**Comment by rassmate** [comment]
@jamesgorman2 any chance for merge soon?
We have verified that this solves our problem in our production environment.

**Review by jamesgorman2 — APPROVED** [review]
LGTM

**Comment by jamesgorman2** [comment]
Sorry, I'm massively behind on things. This one looks good and I'll put a patch out for it.

**Comment by BharathiRajendran01** [comment]
@jamesgorman2  Is the patch out with this fix?

**Comment by jamesgorman2** [comment]
@BharathiRajendran01 yes, this was released in [0.5.3](https://github.com/ReactiveX/RxNetty/releases/tag/0.5.3)

**Pull request merged**
